[versions]
agp = "8.3.0-beta01"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
recyclerView = "1.3.2"
picasso = "2.71828"
gson = "2.10.1"
mockito = "5.6.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
recyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerView" }
picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picasso" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

